### ISSUE TITLE
Data issue and update readme file

### ISSUE THREAD

**Issue by shenwanxiang** [predomics/predomicspkg#11]
@eprifti Hi Edi, thanks for your nice work!

I checked the Table S1 in your paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7062144/#bib48), It seems that the datasets in Table S1 are not as the same datasets in this repo.

The datasets in this repo are all with 1045 features, while the datasets you've used in your paper have different number of features, and none of these datasets contain 1045 features.

![image](https://user-images.githubusercontent.com/21102929/192712562-708061d1-654b-4179-9b36-aeb8ec1af46c.png)

It would be great if you can provideand  creat those datasets you've used as benchmark datasets with pure csv format, thanks!

In addtion, I aslo fixed the installation part of `predomics` package, in the future, it can be very good if you can make it easy to be installed by `install.package('predomics')` in R. Also, I may help you convert your R predomics as Python predomics to make a Pythonic package. 

#### R-version: 4.2

```R
install.packages(c("doSNOW", "foreach", "snow", "yaml","doRNG", "gtools", "glmnet", "pROC", "viridis", "kernlab", "randomForest"))
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("BioQC")

install.packages("testthat")
install.packages("roxygen2")
install.packages("reshape2")

```

**Comment by eprifti** [comment]
Hello @shenwanxiang,
Thanks for the interest in the `predomics` package and your suggestions
- the difference in size comes from the fact that we filtered out variables with no signal in respective datasets. Also there may be future version of the `curatedMetagenomicData` with updated pipelines of metaphlan
- we plan to publish it in cran, which needs time to modify the code to pass all the requirements of CRAN
- please feel free to work on a python module and associate me
- OK for converting the data on csv. I'll note that for the future version.

Best wishes
