### ISSUE TITLE
[Question] Is the Shiny app available?

### ISSUE THREAD

**Issue by AlbanOtt2** [predomics/predomicspkg#12]
Dear Edi,

I am considering to test your approach on my own datasets.
The most efficient way to test might be to use the shiny app you mention here https://github.com/predomics/predomicspkg/blob/9483240ba3a07c4d50efa45aaf0fda368531c5c4/README.md?plain=1#L5

However, I can't find it in this repository and I can't find a dedicated repository.
Is it already available?

Best,
Alban

**Comment by eprifti** [comment]
Hello Alban,
Thanks for your interest. 
The shiny app is accessible for the moment only locally and will be opened soon to the community. There are still some developments to be finalised before release.
In the meantime, I encourage you to use the package's vignettes.
We are working on the documentation and make it more accessible for the users.
